'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
document.documentElement.classList.add('js');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(e=>io.observe(e));
function randomMac(){let a=new Uint8Array(6);crypto.getRandomValues(a);a[0]=2;return [...a].map(x=>x.toString(16).padStart(2,'0')).join(':').toUpperCase()}
$('#heroShuffle').onclick=()=>{$('#heroMac').textContent=randomMac();tone(420)};
const shots=[['00-dashboard.png','An interface, with its whole context.'],['02-mac-control.png','Choose a candidate. See the vendor pattern.'],['05-network-observer.png','Observe the network, not a promise.'],['09-reports.png','A record you can inspect and export.']];
$$('[data-shot]').forEach(b=>b.onclick=()=>{let n=+b.dataset.shot;$$('[data-shot]').forEach(x=>x.setAttribute('aria-selected',x===b));$('#appShot').src='assets/'+shots[n][0];$('#appShot').alt='MAC-OUT 1.1.0 '+['dashboard','MAC control','network observer','reports'][n]+', real app screenshot';$('#shotTitle').textContent=shots[n][1]});
const pipes=[['REQUEST','Start with a known state.','MAC-OUT snapshots the interface and validates the requested address before it starts a change.','GUI → MacManager.apply → interface snapshot'],['EXECUTE','The existing tool does the change.','The backend calls macchanger with validated arguments, handling interface state where needed. MAC-OUT does not replace macchanger.','backend.py → macchanger → Linux interface'],['VERIFY','Read back. Never just assume.','MAC-OUT reads the address exposed by the kernel and compares it with the request. A mismatch triggers an attempt to restore the old address.','/sys/class/net/<interface>/address → compare'],['OBSERVE','Check what happened afterwards.','Renew DHCP, wait for an IP address and test DNS and connectivity. These are local observations, not upstream records.','DHCP → IP → gateway / DNS / connectivity'],['RECORD','Make the change inspectable.','Save before and after snapshots in history. Keep session records and export a report, redacted by default.','history → session → TXT / JSON / CSV / HTML / ZIP']];
$$('[data-pipe]').forEach(b=>b.onclick=()=>{let n=+b.dataset.pipe;$$('[data-pipe]').forEach(x=>x.classList.toggle('active',x===b));$('#pipeIndex').textContent=String(n+1).padStart(2,'0')+' / '+pipes[n][0];$('#pipeTitle').textContent=pipes[n][1];$('#pipeText').textContent=pipes[n][2];$('#pipeCode').textContent=pipes[n][3]});
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
$('#copyInstall').onclick=async()=>{try{await navigator.clipboard.writeText($('#installCode').textContent);toast('Commands copied. Read them before running.')}catch{toast('Copy unavailable. Select the commands to copy.')}};
$('#sourcesOpen').onclick=()=>$('#sourceDialog').showModal();$('#sourcesClose').onclick=()=>$('#sourceDialog').close();
let audio,sound=false;function tone(f=280){if(!sound)return;audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f/2,audio.currentTime+.3);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.4)}
function networkSVG(){return `<svg viewBox="0 0 520 240" role="img" aria-label="Computer sends frames to the local router, which forwards traffic to the internet"><path class="diagram-line" d="M115 100H375"/><rect class="diagram-box" x="10" y="50" width="110" height="100" rx="8"/><rect class="diagram-box" x="210" y="60" width="100" height="80" rx="8"/><circle class="diagram-box" cx="445" cy="100" r="50"/><path d="M445 50V150M395 100H495" stroke="#6b8053" fill="none"/><ellipse cx="445" cy="100" rx="23" ry="50" fill="none" stroke="#6b8053"/><text x="65" y="92" text-anchor="middle">YOUR DEVICE</text><text x="65" y="113" text-anchor="middle" style="fill:#d8f36a">MAC ADDRESS</text><text x="260" y="105" text-anchor="middle">ROUTER</text><text x="445" y="179" text-anchor="middle">INTERNET</text><text x="165" y="195" text-anchor="middle" style="fill:#d8f36a">LOCAL LINK</text><text x="365" y="218" text-anchor="middle" style="fill:#a0aba9">LAYER-2 ADDRESSES CHANGE AT ROUTED HOPS</text><rect class="packet packet-flow" x="120" y="96" width="13" height="8" rx="2"/><rect class="packet packet-flow" x="120" y="96" width="13" height="8" rx="2" style="animation-delay:-1.5s"/></svg>`}
const scenes=[
{label:'A LOCAL IDENTITY',title:'Six bytes.<br><em>A whole story.</em>',text:'Before a device reaches the internet, it has to communicate on a local link. That is where a MAC address enters the picture.',note:'Media Access Control. This presentation is an educational model, not a view of your network.',art:()=>networkSVG()},
{label:'THE ADDRESS, DECODED',title:'48 bits.<br><em>Not a fingerprint.</em>',text:'A common Ethernet or Wi-Fi MAC address has six octets, usually written as twelve hexadecimal digits. A universally assigned prefix can identify an address-block owner, not certify the hardware.',note:'The diagram shows a common 24-bit OUI. IEEE also assigns longer prefixes. A software-selected address can copy a pattern.',art:()=>`<div class="scene-big-number">48<span style="font-size:24px;letter-spacing:0"> bits</span></div><div class="byte-row">${['00','08','32','91','B6','2E'].map(x=>`<span class="byte">${x}</span>`).join('')}</div><div class="brackets"><span>COMMON VENDOR PREFIX / 24 BITS</span><span>REMAINING ADDRESS / 24 BITS</span></div>`},
{label:'TWO BITS WITH A JOB',title:'Tiny switches.<br><em>Different meanings.</em>',text:'In the first octet, the two least-significant bits distinguish individual from group addresses and universal from local administration. Tap the orange bits to explore.',note:'For a locally administered unicast example, the local bit is 1 and the group bit is 0. The entire address is then locally administered.',art:()=>`<div class="demo-label">INTERACTIVE / FIRST OCTET, MOST SIGNIFICANT BIT AT LEFT</div><div class="bit-grid">${[7,6,5,4,3,2,1,0].map(i=>i<2?`<button class="bit" data-bit="${i}" aria-label="Toggle ${i?'local':'group'} bit">${i?1:0}<small>${i?'LOCAL':'GROUP'}</small></button>`:`<span class="bit">0<small>BIT ${i}</small></span>`).join('')}</div><div id="bitResult" class="bit-result">02 / LOCALLY ADMINISTERED / UNICAST</div>`},
{label:'WHAT ACTUALLY CHANGES',title:'A new local address.<br><em>Same wider world.</em>',text:'Changing the current MAC changes the address your interface uses on the local link. It does not rewrite the hardware, or automatically change your public IP, accounts or browser identity.',note:'The permanent address may still be exposed by the driver. Frames do not carry your original device MAC end-to-end across routed networks.',art:()=>`<div class="network-model">${networkSVG()}</div><div id="demoAddress" class="demo-mac">02:7A:4C:91:B6:2E</div><button class="scene-button" id="demoChange">Change the illustrated address ↻</button>`},
{label:'WHY EXPERIMENT?',title:'Privacy is one reason.<br><em>Understanding is another.</em>',text:'Randomization can reduce the use of one stable local identifier across connections. In an authorized lab, changing an address also lets you study DHCP, connection recovery and how a network responds.',note:'It is not anonymity. Changing too often can disrupt authentication, leases and access rules. Avoid address collisions.',art:()=>`<div class="model-cards"><div class="model-card"><span>01 / PRIVACY</span><strong>Less stable.</strong><p>Reduce one recurring local identifier. Other identifying signals remain.</p></div><div class="model-card"><span>02 / LEARNING</span><strong>More visible.</strong><p>Compare a controlled before and after on equipment you may test.</p></div></div>`},
{label:'MAC-OUT ON TOP OF MACCHANGER',title:'The tool changes it.<br><em>The app adds context.</em>',text:'macchanger performs the MAC change. MAC-OUT wraps that tool with a GTK interface, validated requests, read-back verification, observation, profiles and records.',note:'Python zipapp, not a separate compiled engine. Slow operations run outside the GUI thread. No user-typed shell command is executed.',art:()=>`<div class="layer-stack"><div class="layer"><span>01 / UI</span><div><strong>MAC-OUT</strong><small>GTK 3 · profiles · rotation · reports</small></div></div><div class="layer"><span>02 / APP</span><div><strong>Application services</strong><small>Validate · snapshot · verify · observe · record</small></div></div><div class="layer"><span>03 / OS</span><div><strong>macchanger + Linux</strong><small>Command backend · ip · nmcli · kernel read-back</small></div></div></div>`},
{label:'NEVER TRUST THE REQUEST ALONE',title:'Requested ≠ applied.<br><em>Until verified.</em>',text:'For an explicit target, MAC-OUT reads the actual interface address and compares it with the request. A mismatch triggers a recovery attempt and a failure report. Try both paths.',note:'Simulation only. A driver can refuse a change or a restore. The real result must be read from the interface.',art:()=>`<div class="verify-demo"><div class="verify-head"><span>SAFE BROWSER SIMULATION</span><label><input type="checkbox" id="failDriver"> Driver refuses</label></div><div class="verify-steps"><span>REQUEST</span><span>EXECUTE</span><span>READ BACK</span><span>COMPARE</span></div><div class="verify-macs"><span>BEFORE <code>02:11:22:33:44:55</code></span><span>REQUEST <code>02:7A:4C:91:B6:2E</code></span><span>READ BACK <code id="readback">Waiting</code></span></div><div id="verifyResult">Ready. No real interface is modified.</div><button class="scene-button" id="runVerify">Run the simulation ▶</button></div>`},
{label:'VENDOR PATTERNS, HONESTLY',title:'A prefix match.<br><em>Not a disguise guarantee.</em>',text:'Choose a synthetic address from a vendor series. MAC-OUT labels a recognized globally administered prefix beside the MAC. A locally administered address is not treated as a manufacturer identity.',note:'These are generated candidates, not addresses collected from devices. A matching prefix does not make a device genuine hardware from that vendor.',art:()=>`<div class="demo-label">SELECT A SYNTHETIC CANDIDATE / ILLUSTRATED CISCO PREFIX</div><div class="vendor-list">${['00:08:32:91:B6:2E','00:08:32:A4:19:70','00:08:32:52:C8:10','00:08:32:6F:30:8A'].map((m,i)=>`<button data-vendor="${m}" class="${i?'':'selected'}">${m}<span>SELECT ${i+1}</span></button>`).join('')}</div><div class="vendor-selected" id="vendorSelected">00:08:32:91:B6:2E (Cisco)</div>`},
{label:'WHERE THE VIEW ENDS',title:'Observe the local.<br><em>Do not invent the remote.</em>',text:'The observer can show local addresses, Wi-Fi state and connectivity test results. It cannot inspect what a router, ISP or campus access system records. Reachability is not proof of privacy.',note:'Drivers may reject MAC changes. Persistence depends on NetworkManager or a boot-only fallback. Use only networks where you have permission.',art:()=>`<div class="view-mask"><div class="view-zone"><span>VISIBLE HERE</span><h3>Your interface.</h3><p>MAC · IP · gateway<br>DNS checks<br>Connection state</p></div><div class="view-zone"><span>NOT VISIBLE HERE</span><h3>Upstream records.</h3><p>Router logs<br>ISP records<br>Campus access logs</p></div></div>`},
{label:'THE EXPERIMENT LEAVES A RECORD',title:'Compare. Diagnose.<br><em>Share carefully.</em>',text:'Keep history and session records, then export TXT, JSON, CSV, HTML or ZIP. Reports are redacted by default, but review every report before sharing it.',note:'The export in v1.1.0 restores desktop-user ownership when launched with sudo. The browser example below contains invented demonstration data only.',art:()=>`<div class="report-demo"><div class="tiny">DEMONSTRATION REPORT / NOT LIVE DATA</div><h3>Before / After</h3><div class="report-line"></div><span class="redacted" data-private="MAC: 02:7A:4C:91:B6:2E">MAC: [redacted]</span><span class="redacted" data-private="SSID: Example-Lab">SSID: [redacted]</span><span class="redacted" data-private="IP: 192.0.2.10">IP: [redacted]</span><div class="report-line" style="width:65%"></div><button id="redactionToggle" aria-pressed="true">Redaction on · toggle</button></div>`},
{label:'THE TAKEAWAY',title:'Control the change.<br><em>Understand the result.</em>',text:'MAC-OUT brings the request, the actual applied state and the observed network behavior into one place. Keep the claims local. Keep the experiments authorized.',note:'Made by Arnab Mandal. Special thanks to Dr. Nabanita Ganguly. Designed for CA-1, MAKAUT WB.',art:()=>`<div class="closing-art"><strong>MAC-OUT</strong></div><div class="scene-links"><a href="https://github.com/vio137/macout/releases/tag/v1.1.0">Get the app ↗</a><a href="https://github.com/vio137/macout">Read the source ↗</a><button id="stageSources">Technical sources ↗</button></div>`},
{label:"MAC VS IP",title:"Same packet.<br><em>Different envelopes.</em>",text:"A MAC identifies a link-layer endpoint. An IP address helps route a packet between networks. A router receives one frame and sends the packet onto the next link in another frame.",note:"MAC addresses are local-link identifiers, not internet-wide authentication.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">LOCAL LINK</span><code>Laptop MAC \u2192 router MAC</code></div><div><span class=\"tiny\">NEXT LINK</span><code>Router MAC \u2192 next-hop MAC</code></div><div><span class=\"tiny\">NETWORK LAYER</span><code>IP packet forwarded between links</code></div></div>"},
{label:"MEET GNU MACCHANGER",title:"One tool.<br><em>Four useful switches.</em>",text:"macchanger is the command-line engine beneath MAC-OUT. Display, randomize, set and restore are different requests to that engine.",note:"Examples only. Changes need permission, privileges and driver support.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">DISPLAY</span><code>macchanger -s wlan0</code></div><div><span class=\"tiny\">RANDOM</span><code>macchanger -r wlan0</code></div><div><span class=\"tiny\">EXPLICIT</span><code>macchanger -m 02:7a:4c:91:b6:2e wlan0</code></div><div><span class=\"tiny\">PERMANENT</span><code>macchanger -p wlan0</code></div></div>"},
{label:"THE STRATEGY TRANSLATOR",title:"Six choices.<br><em>Three backend modes.</em>",text:"MAC-OUT resolves your strategy before changing anything. Random and permanent use dedicated macchanger modes. The other strategies produce an explicit address in Python.",note:"Vendor candidates are synthetic. A vendor pattern is not proof of manufacturer identity.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">RANDOM / PERMANENT</span><code>-r / -p</code></div><div><span class=\"tiny\">LOCAL / VENDOR / PATTERN</span><code>generate target \u2192 -m TARGET</code></div><div><span class=\"tiny\">FIXED</span><code>normalize + reject multicast \u2192 -m TARGET</code></div></div>"},
{label:"BEFORE THE CHANGE",title:"Know the starting point.<br><em>Before you disturb it.</em>",text:"Validate the interface and target. Remember the original address. Capture the current MAC, link state, IP addresses, gateway and optional connectivity results.",note:"Commands use validated argument lists with subprocess.run. No shell expansion of user input.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">INTERFACE</span><code>/sys/class/net/IFACE/address</code></div><div><span class=\"tiny\">LINK &amp; IP</span><code>ip -j addr show dev IFACE</code></div><div><span class=\"tiny\">DEFAULT ROUTE</span><code>ip -j route show default dev IFACE</code></div></div>"},
{label:"THE ACTUAL CHANGE",title:"Down. Change. Up.<br><em>Only when needed.</em>",text:"If the interface was up, the backend takes it down, calls macchanger and attempts to bring it back up in a finally block. An interface that began down remains down.",note:"The driver can reject the request. Restoring link state is attempted even when macchanger fails.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">IF PREVIOUSLY UP</span><code>ip link set dev wlan0 down</code></div><div><span class=\"tiny\">EXPLICIT TARGET</span><code>macchanger -m 02:7a:4c:91:b6:2e wlan0</code></div><div><span class=\"tiny\">FINALLY, IF PREVIOUSLY UP</span><code>ip link set dev wlan0 up</code></div></div>"},
{label:"READ-BACK IS THE TRUTH",title:"Exit code is not enough.<br><em>Read the interface.</em>",text:"After the command, Python reads the actual address. Explicit targets are compared with the observed value. A mismatch or unexpected change triggers an attempt to recover the old address.",note:"Random mode has no preselected target to compare. A recovery attempt can fail; inspect the observed state and logs.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">REQUEST</span><code>02:7a:4c:91:b6:2e</code></div><div><span class=\"tiny\">READ BACK</span><code>/sys/class/net/wlan0/address</code></div><div><span class=\"tiny\">ON MISMATCH</span><code>reapply old MAC \u2192 record failure</code></div></div>"},
{label:"RECONNECT, CONDITIONALLY",title:"A changed MAC.<br><em>May mean a lost lease.</em>",text:"If the prior snapshot had dynamic IPv4 or a connected NetworkManager state, MAC-OUT requests renewal. It tries supported clients in order and waits for the link and address.",note:"These are fallback paths, not a script that always runs every command.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">FIRST</span><code>nmcli device reapply IFACE \u2192 reconnect</code></div><div><span class=\"tiny\">NEXT AVAILABLE</span><code>networkctl renew IFACE</code></div><div><span class=\"tiny\">LAST AVAILABLE</span><code>dhclient -r IFACE \u2192 dhclient IFACE</code></div></div>"},
{label:"CONNECTIVITY IS SEPARATE",title:"Applied address.<br><em>Degraded connection?</em>",text:"A MAC operation can succeed while connection recovery times out. The observer separately checks local addressing, gateway reachability, DNS and TCP connectivity.",note:"Reachability is not proof of privacy. No upstream system logs are accessible to the app.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">GATEWAY</span><code>ping -c 1 -W 2 GATEWAY</code></div><div><span class=\"tiny\">DNS</span><code>Python getaddrinfo(example.com, 443)</code></div><div><span class=\"tiny\">TCP</span><code>IPv4 1.1.1.1:443 / IPv6 Cloudflare:443</code></div></div>"},
{label:"PROFILES + ROTATION",title:"Repeat the experiment.<br><em>Not the guesswork.</em>",text:"Profiles store a strategy and settings in JSON. Rotation uses a Python scheduler and supported reconnect events to call the same validated apply pipeline. Pause, stop or rotate now.",note:"Rapid changes can disrupt leases, authentication and access rules. Rotation is not a new MAC-changing engine.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">PROFILE</span><code>strategy + target rules + options</code></div><div><span class=\"tiny\">SCHEDULER</span><code>interval / supported reconnect trigger</code></div><div><span class=\"tiny\">EXECUTION</span><code>MacManager.apply \u2192 read back \u2192 history</code></div></div>"},
{label:"PERSISTENCE IS OPTIONAL",title:"One profile.<br><em>Or one boot action.</em>",text:"NetworkManager persistence modifies the active connection profile. Without it, the fallback systemd service reapplies saved entries at boot, not on every reconnect or resume.",note:"Removing persistence does not itself restore the current MAC. Restore is a separate action.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">NETWORKMANAGER</span><code>nmcli connection modify CONNECTION 802-11-wireless.cloned-mac-address TARGET</code></div><div><span class=\"tiny\">SYSTEMD</span><code>systemctl enable macout-persist.service</code></div><div><span class=\"tiny\">BOOT ENTRY</span><code>macout --apply-persistent</code></div></div>"},
{label:"THE FUNCTION MAP",title:"One app.<br><em>Several ways to learn.</em>",text:"Dashboard and Interfaces inspect state. MAC Control applies changes. Profiles and Rotation repeat them. Observer and Diagnostics explain the aftermath. History, Logs and Reports preserve evidence.",note:"Settings configure behavior; About explains the environment. Most record and UI features are Python, not shell commands.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">CONTROL</span><code>MAC Control \u00b7 Profiles \u00b7 Rotation</code></div><div><span class=\"tiny\">OBSERVE</span><code>Dashboard \u00b7 Interfaces \u00b7 Observer \u00b7 Diagnostics</code></div><div><span class=\"tiny\">RECORD</span><code>History \u00b7 Logs \u00b7 Reports \u00b7 Sessions</code></div></div>"},
{label:"WHY MAC-OUT EXISTS",title:"Less manual glue.<br><em>More inspectable evidence.</em>",text:"macchanger remains the engine. MAC-OUT combines validated inputs, generated targets, before/after snapshots, reusable profiles, conditional recovery, scheduling and export in one desktop workflow.",note:"No promise of anonymity, access-rule bypass or universal driver support. Use authorized equipment.",art:()=>"<div class=\"command-cards\"><div><span class=\"tiny\">REPEATABILITY</span><code>Save strategy + settings</code></div><div><span class=\"tiny\">ACCOUNTABILITY</span><code>Requested vs observed state</code></div><div><span class=\"tiny\">TEACHING</span><code>Inspect commands + local evidence</code></div></div>"}
];
scenes.push(scenes.splice(10,1)[0]);
let current=0,busy=false,playTimer,playing=false,verifyToken=0,lastFocus;
function renderScene(){verifyToken++;let s=scenes[current];$('#scene').innerHTML=`<div class="scene-wrap"><div class="scene-copy"><div class="eyebrow">${String(current+1).padStart(2,'0')} / ${s.label}</div><h2 tabindex="-1">${s.title}</h2><p>${s.text}</p><div class="scene-note">${s.note}</div></div><div class="scene-art">${s.art()}</div></div>`;$('#scene').scrollTop=0;$('.stage-count').textContent=' / '+scenes.length;$('#sceneNumber').textContent=String(current+1).padStart(2,'0');$('#stageProgress').style.width=((current+1)/scenes.length*100)+'%';$('#prevScene').disabled=current===0;$('#nextScene').disabled=current===scenes.length-1;$$('[data-chapter]').forEach(b=>b.classList.toggle('active',+b.dataset.chapter===current));bindScene();if(playing&&current===scenes.length-1)stopPlay()}
function go(n){if(busy||n<0||n>=scenes.length||n===current)return;busy=true;$('#chapters').hidden=true;$('#chapterOpen').setAttribute('aria-expanded','false');tone(190+n*25);if(reduced){current=n;renderScene();busy=false;return}$('#stage').classList.remove('iris','shutter');$('#stage').classList.add(['wipe','iris','shutter'][n%3]);$('#stage').classList.add('stage-transition');setTimeout(()=>{current=n;renderScene()},340);setTimeout(()=>{$('#stage').classList.remove('stage-transition');busy=false},800)}
function openStage(n=0){lastFocus=document.activeElement;current=n;$('#stage').hidden=false;$('main').inert=true;$('header').inert=true;document.body.style.overflow='hidden';renderScene();$('#nextScene').focus();history.replaceState(null,'','#presentation');resizeCanvas()}
function closeStage(){verifyToken++;stopPlay();$('#stage').hidden=true;$('main').inert=false;$('header').inert=false;document.body.style.overflow='';if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});history.replaceState(null,'',location.pathname);lastFocus?.focus()}
$$('[data-stage]').forEach(b=>b.onclick=()=>openStage(+b.dataset.stage));$('#closeStage').onclick=closeStage;$('#stageHome').onclick=e=>{e.preventDefault();closeStage()};$('#nextScene').onclick=()=>go(current+1);$('#prevScene').onclick=()=>go(current-1);
$('#chapters').innerHTML=scenes.map((s,i)=>`<button data-chapter="${i}">${String(i+1).padStart(2,'0')} / ${s.label}</button>`).join('');$$('[data-chapter]').forEach(b=>b.onclick=()=>go(+b.dataset.chapter));$('#chapterOpen').onclick=()=>{$('#chapters').hidden=!$('#chapters').hidden;$('#chapterOpen').setAttribute('aria-expanded',!$('#chapters').hidden)};
function stopPlay(){clearInterval(playTimer);playing=false;$('#autoPlay').textContent='Play';$('#autoPlay').setAttribute('aria-pressed','false')}
$('#autoPlay').onclick=()=>{if(playing){stopPlay();return}if(current===scenes.length-1)go(0);playing=true;$('#autoPlay').textContent='Pause';$('#autoPlay').setAttribute('aria-pressed','true');playTimer=setInterval(()=>go(current+1),14000)};
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='Sound '+(sound?'on':'off');$('#sound').setAttribute('aria-pressed',sound);tone(440)};
$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else $('#stage').requestFullscreen().catch(()=>toast('Fullscreen is not supported here.'))};
document.addEventListener('keydown',e=>{if($('#stage').hidden||$('#sourceDialog').open)return;if(e.key==='Escape')closeStage();if(e.target.matches('input,button,a')&&(e.key===' '||e.key==='Enter'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(current+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}if(e.key==='Home')go(0);if(e.key==='End')go(scenes.length-1);if(e.key==='Tab'){let fs=$$('#stage button:not(:disabled),#stage a,#stage input').filter(x=>x.getClientRects().length);let first=fs[0],last=fs.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
let touchStart;$('#scene').addEventListener('touchstart',e=>{touchStart=[e.touches[0].clientX,e.touches[0].clientY]},{passive:true});$('#scene').addEventListener('touchend',e=>{if(!touchStart)return;let dx=e.changedTouches[0].clientX-touchStart[0],dy=e.changedTouches[0].clientY-touchStart[1];if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.6)go(current+(dx<0?1:-1));touchStart=null},{passive:true});
function bindScene(){if($('#demoChange'))$('#demoChange').onclick=()=>{$('#demoAddress').textContent=randomMac();tone(400)};$$('[data-bit]').forEach(b=>b.onclick=()=>{let value=b.firstChild.textContent==='1'?0:1;b.firstChild.textContent=value;let local=+$('.bit[data-bit="1"]').firstChild.textContent,group=+$('.bit[data-bit="0"]').firstChild.textContent;$('#bitResult').textContent=(local*2+group).toString(16).padStart(2,'0').toUpperCase()+' / '+(local?'LOCALLY':'UNIVERSALLY')+' ADMINISTERED / '+(group?'GROUP':'UNICAST');tone(250+value*150)});$$('[data-vendor]').forEach(b=>b.onclick=()=>{$$('[data-vendor]').forEach(x=>x.classList.toggle('selected',x===b));$('#vendorSelected').textContent=b.dataset.vendor+' (Cisco)';tone(300)});if($('#runVerify'))$('#runVerify').onclick=async()=>{let token=++verifyToken,fail=$('#failDriver').checked;$('#runVerify').disabled=true;$('#failDriver').disabled=true;$('#readback').textContent='Waiting';$('#verifyResult').textContent='Snapshot saved. Request validated.';$$('.verify-steps span').forEach(x=>x.classList.remove('done'));for(let i=0;i<4;i++){await new Promise(r=>setTimeout(r,reduced?20:650));if(token!==verifyToken)return;$$('.verify-steps span')[i].classList.add('done');tone(200+i*100);if(i===2)$('#readback').textContent=fail?'02:11:22:33:44:55':'02:7A:4C:91:B6:2E'}$('#verifyResult').textContent=fail?'Mismatch. This simulated driver refused the request. Old address retained; failure recorded.':'Verified match. Next: renew DHCP, check connectivity and record the result.';$('#verifyResult').style.color=fail?'var(--orange)':'var(--lime)';$('#runVerify').disabled=false;$('#failDriver').disabled=false};if($('#redactionToggle'))$('#redactionToggle').onclick=()=>{let on=$('#redactionToggle').getAttribute('aria-pressed')==='true';$('#redactionToggle').setAttribute('aria-pressed',!on);$('#redactionToggle').textContent='Redaction '+(on?'off':'on')+' · toggle';$$('[data-private]').forEach(x=>x.textContent=on?x.dataset.private:x.dataset.private.split(':')[0]+': [redacted]');tone(400)};if($('#stageSources'))$('#stageSources').onclick=()=>$('#sourceDialog').showModal()}
// Custom canvas graphics: flowing local frames and perspective address lanes.
const heroCanvas=$('#network'),hc=heroCanvas.getContext('2d'),stageCanvas=$('#stageCanvas'),sc=stageCanvas.getContext('2d');let hw,hh,sw,sh,frame=0,visibleHero=true;new IntersectionObserver(es=>visibleHero=es[0].isIntersecting).observe(heroCanvas);
function size(c){let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;c.getContext('2d').setTransform(d,0,0,d,0,0);return [r.width,r.height]}
function resizeCanvas(){[hw,hh]=size(heroCanvas);if(!$('#stage').hidden)[sw,sh]=size(stageCanvas)}new ResizeObserver(resizeCanvas).observe(heroCanvas);window.addEventListener('resize',resizeCanvas);resizeCanvas();
function heroDraw(t){hc.clearRect(0,0,hw,hh);let cx=hw/2,cy=hh*.42;hc.strokeStyle='#475e4260';for(let r=65;r<240;r+=45){hc.beginPath();hc.ellipse(cx,cy,r,r*.38,0,0,Math.PI*2);hc.stroke()}for(let i=0;i<8;i++){let a=i*Math.PI/4,r=155,ex=cx+Math.cos(a)*r,ey=cy+Math.sin(a)*r*.45;hc.strokeStyle='#76945d77';hc.beginPath();hc.moveTo(cx,cy);hc.lineTo(ex,ey);hc.stroke();hc.fillStyle='#1f3024';hc.strokeStyle='#75925e';hc.strokeRect(ex-12,ey-12,24,24);let q=reduced?.5:((t*.00016+i*.15)%1);hc.fillStyle='#d8f36a';hc.beginPath();hc.arc(cx+(ex-cx)*q,cy+(ey-cy)*q,3,0,Math.PI*2);hc.fill()}hc.fillStyle='#c5d4b1';hc.font='9px monospace';hc.textAlign='center';hc.fillText('LOCAL LINK / FRAME FLOW',cx,hh*.14);hc.strokeStyle='#b2cd6c';hc.strokeRect(cx-26,cy-18,52,36);hc.fillStyle='#d8f36a';hc.font='14px monospace';hc.fillText('NIC',cx,cy+5)}
function stageDraw(t){sc.clearRect(0,0,sw,sh);let horizon=sh*.46;sc.strokeStyle='#83a05b16';for(let i=-8;i<9;i++){sc.beginPath();sc.moveTo(sw*.5+i*20,horizon);sc.lineTo(sw*.5+i*220,sh);sc.stroke()}for(let i=0;i<9;i++){let p=(i/9+(reduced?0:t*.00003))%1,y=horizon+(sh-horizon)*p*p;sc.beginPath();sc.moveTo(0,y);sc.lineTo(sw,y);sc.stroke()}let g=sc.createRadialGradient(sw*.75,sh*.35,0,sw*.75,sh*.35,sw*.55);g.addColorStop(0,'#7b9e3822');g.addColorStop(1,'#00000000');sc.fillStyle=g;sc.fillRect(0,0,sw,sh);for(let i=0;i<14;i++){let x=((i*139+(reduced?0:t*.007))%(sw+150))-75,y=sh*.23+(i%5)*65;sc.fillStyle='#d8f36a18';sc.fillRect(x,y,35,1)}}
function animate(t){if(!document.hidden){if(visibleHero)heroDraw(t);if(!$('#stage').hidden)stageDraw(t);frame++}requestAnimationFrame(animate)}requestAnimationFrame(animate);
if(location.hash==='#presentation')openStage();
window.addEventListener('hashchange',()=>{if(location.hash==='#presentation'&&$('#stage').hidden)openStage()});
